"""add complaint sla escalation fields

Revision ID: 5e04cf9a7732
Revises: 001_initial
Create Date: 2026-09-25 23:36:46.530423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e04cf9a7732'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'complaints',
    sa.Column(
        'escalation_count',
        sa.Integer(),
        nullable=False,
        server_default='0'
    )
)
    op.create_index(op.f('ix_complaints_sla_deadline'), 'complaints', ['sla_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_sla_deadline'), table_name='complaints')
    op.drop_column('complaints', 'escalation_count')
    op.drop_column('complaints', 'last_escalation_at')
    op.drop_column('complaints', 'sla_deadline')
    # ### end Alembic commands ###
