"""add authority email

Revision ID: c767d926cf3a
Revises: 5e04cf9a7732
Create Date: 2026-09-25 23:50:10.871116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c767d926cf3a'
down_revision: Union[str, None] = '5e04cf9a7732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'authorities',
    sa.Column(
        'email',
        sa.String(length=255),
        nullable=False,
        server_default='admin@civicai.local'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorities', 'email')
    # ### end Alembic commands ###
